import {
  chmodSync,
  mkdirSync,
  mkdtempSync,
  readdirSync,
  readFileSync,
  renameSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { join } from "node:path";
import { openDocumentsDir } from "../paths.js";
import { removeOpenDocumentContentForProcess } from "./openDocumentContent.js";
import { processIsRunning } from "./processLiveness.js";

/**
 * What the application tells other processes about the documents it has open.
 *
 * One file per window, written by the main process and read by anything that wants to know —
 * today, the MCP server. The shape is deliberately small: enough to name a document and to prove
 * permission for it, and nothing else. **No document text ever passes through here.** Text has one
 * route out of this program, through the bounds in `output/budget.ts`, and a second copy of a
 * document living in a metadata file would be neither bounded nor accounted for.
 */

export type OpenDocumentKind = "pdf" | "markdown";

export interface OpenDocumentRecord {
  /** Unique for as long as the tab exists. Generated by the window that owns it. */
  tabId: string;
  kind: OpenDocumentKind;
  name: string;
  /**
   * Where the document came from, or `null` for one that has never been saved.
   *
   * **Private to this file and to permission checks.** It is what lets a reader prove read consent
   * for a document that is not yet indexed. It is never part of a tool reply: an agent asked what
   * is open, not where this person keeps their files.
   */
  path: string | null;
  pageCount: number;
  /** The visible PDF page, or null for a Markdown tab. */
  currentPage: number | null;
  /** The document's identity in the index, or `null` while it is not indexed. */
  contentHash: string | null;
  /** Whether the separate private content file exists for this tab. */
  hasContentSnapshot: boolean;
  /** UTF-16 code units and UTF-8 bytes available in that separate file. */
  contentChars: number;
  contentBytes: number;
  /** True when the open buffer exceeded the local snapshot ceiling. */
  snapshotTruncated: boolean;
  /**
   * Whether the window holds changes not yet written to disk.
   *
   * Reported rather than acted on. Some unsaved changes are visible to a reader and some are not —
   * see the tool descriptions — so what this supports is an honest sentence, not a decision.
   */
  unsavedChanges: boolean;
}

export interface WindowSnapshot {
  version: 2;
  /** The application process. What makes a file from a crashed run recognisable as one. */
  pid: number;
  windowId: number;
  /** Increases each time this window is focused, so the most recent one is the largest. */
  focusedAt: number;
  writtenAt: string;
  activeTabId: string | null;
  documents: readonly OpenDocumentRecord[];
}

export interface OpenDocumentEntry extends OpenDocumentRecord {
  /** Opaque, stable while the tab is open, and meaningless to anything but this program. */
  ref: string;
  window: number;
  /** Owning process, used only to locate the private content snapshot. Never returned by a tool. */
  process: number;
  /** The front tab of its own window. Several may be true at once. */
  activeInWindow: boolean;
  /** The one document a person would call "the one I have open". At most one is true. */
  active: boolean;
}

export interface OpenDocumentsView {
  windows: number;
  activeRef: string | null;
  /** Active first, then most recently focused window first, then the window's own tab order. */
  documents: OpenDocumentEntry[];
  /** Files that could not be understood. Counted rather than swallowed, and never fatal. */
  unreadableWindows: number;
}

const EMPTY: OpenDocumentsView = { windows: 0, activeRef: null, documents: [], unreadableWindows: 0 };

/** Only files this program wrote, and only ones whose name still says which process owns them. */
const SNAPSHOT_FILE = /^(\d+)-(\d+)\.json$/;

/**
 * A reference to one open document.
 *
 * The process and the window are in it because a tab identifier is only unique inside the window
 * that made it, and two application processes can exist at once. Opaque on purpose: it is a handle
 * to pass back, not a fact to parse, and it discloses nothing about the filesystem.
 */
export function openDocumentReference(pid: number, windowId: number, tabId: string): string {
  return `${pid}-${windowId}:${tabId}`;
}

function fileNameFor(pid: number, windowId: number): string {
  return `${pid}-${windowId}.json`;
}

function isMissing(error: unknown): boolean {
  return typeof error === "object" && error !== null && "code" in error && error.code === "ENOENT";
}

/**
 * Replace one window's record, atomically and privately.
 *
 * Written into a directory this call creates and renamed onto the target, so a reader never sees a
 * half-written file and an interrupted write leaves the previous record intact. The staging
 * directory is a sibling, so the rename stays within one filesystem and is therefore atomic. This
 * is the same arrangement the consent record uses, for the same reasons — including `mkdtemp`
 * rather than a predictable name, so this can never write through a link somebody else placed.
 *
 * Mode `0600`: which documents a person has open is nobody else's business on a shared machine.
 */
export function writeOpenDocuments(dataDir: string, snapshot: WindowSnapshot): void {
  const directory = openDocumentsDir(dataDir);
  mkdirSync(directory, { recursive: true });
  let staging: string | null = null;
  try {
    staging = mkdtempSync(join(directory, ".writing-"));
    const pending = join(staging, "snapshot.json");
    // `wx` is `O_CREAT | O_EXCL`: it creates or fails, and never follows a link.
    writeFileSync(pending, `${JSON.stringify(snapshot)}\n`, { encoding: "utf8", mode: 0o600, flag: "wx" });
    chmodSync(pending, 0o600);
    renameSync(pending, join(directory, fileNameFor(snapshot.pid, snapshot.windowId)));
  } finally {
    // Only what this call created, and only ever the directory it made.
    if (staging !== null) rmSync(staging, { recursive: true, force: true });
  }
}

/** Forget one window. Called when it closes; a window that was never recorded is not an error. */
export function removeOpenDocuments(dataDir: string, pid: number, windowId: number): void {
  rmSync(join(openDocumentsDir(dataDir), fileNameFor(pid, windowId)), { force: true });
}

/**
 * Forget every window of one process.
 *
 * Called as the application quits, so a clean exit leaves nothing for a reader to find. Scoped to
 * the given process: another application instance's windows are not this one's to clear away.
 */
export function removeOpenDocumentsForProcess(dataDir: string, pid: number): void {
  for (const { file, snapshotPid } of listSnapshotFiles(dataDir)) {
    if (snapshotPid === pid) rmSync(file, { force: true });
  }
}

function listSnapshotFiles(dataDir: string): Array<{ file: string; snapshotPid: number; windowId: number }> {
  const directory = openDocumentsDir(dataDir);
  let entries: string[];
  try {
    entries = readdirSync(directory);
  } catch (error) {
    if (isMissing(error)) return [];
    throw error;
  }
  return entries.flatMap((entry) => {
    const matched = SNAPSHOT_FILE.exec(entry);
    if (matched === null) return [];
    return [{ file: join(directory, entry), snapshotPid: Number(matched[1]), windowId: Number(matched[2]) }];
  });
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function isNonNegativeInteger(value: unknown): value is number {
  return typeof value === "number" && Number.isSafeInteger(value) && value >= 0;
}

/**
 * Read one file back into a snapshot, or refuse it.
 *
 * A file this program wrote a moment ago should always parse, so anything else is either a
 * different version of MarkPDF, a partially written file from a build without the atomic rename,
 * or something a person edited. None of those is worth an exception: this describes what is on a
 * screen, not what somebody has permitted, so a file that cannot be understood is skipped and
 * counted while the windows around it still answer.
 */
function readSnapshot(file: string): WindowSnapshot | null {
  let parsed: unknown;
  try {
    parsed = JSON.parse(readFileSync(file, "utf8"));
  } catch {
    return null;
  }
  if (!isRecord(parsed) || parsed.version !== 2) return null;
  if (typeof parsed.pid !== "number" || typeof parsed.windowId !== "number") return null;
  if (typeof parsed.focusedAt !== "number" || typeof parsed.writtenAt !== "string") return null;
  if (parsed.activeTabId !== null && typeof parsed.activeTabId !== "string") return null;
  if (!Array.isArray(parsed.documents)) return null;

  const documents: OpenDocumentRecord[] = [];
  for (const entry of parsed.documents) {
    if (!isRecord(entry)) return null;
    const {
      tabId,
      kind,
      name,
      path,
      pageCount,
      currentPage,
      contentHash,
      hasContentSnapshot,
      contentChars,
      contentBytes,
      snapshotTruncated,
      unsavedChanges,
    } = entry;
    if (typeof tabId !== "string" || typeof name !== "string") return null;
    if (kind !== "pdf" && kind !== "markdown") return null;
    if (path !== null && typeof path !== "string") return null;
    if (!isNonNegativeInteger(pageCount) || typeof unsavedChanges !== "boolean") return null;
    let checkedCurrentPage: number | null;
    if (kind === "pdf") {
      if (!isNonNegativeInteger(currentPage) || currentPage < 1 || currentPage > pageCount) return null;
      checkedCurrentPage = currentPage;
    } else {
      if (currentPage !== null) return null;
      checkedCurrentPage = null;
    }
    if (contentHash !== null && typeof contentHash !== "string") return null;
    if (typeof hasContentSnapshot !== "boolean") return null;
    if (!isNonNegativeInteger(contentChars) || !isNonNegativeInteger(contentBytes)) return null;
    if (typeof snapshotTruncated !== "boolean") return null;
    documents.push({
      tabId,
      kind,
      name,
      path,
      pageCount,
      currentPage: checkedCurrentPage,
      contentHash,
      hasContentSnapshot,
      contentChars,
      contentBytes,
      snapshotTruncated,
      unsavedChanges,
    });
  }

  return {
    version: 2,
    pid: parsed.pid,
    windowId: parsed.windowId,
    focusedAt: parsed.focusedAt,
    writtenAt: parsed.writtenAt,
    activeTabId: parsed.activeTabId,
    documents,
  };
}

/**
 * Every document open in every live window, with one of them marked active.
 *
 * Read on every call rather than once, for the same reason the consent record is: a session lasts
 * as long as the client does, and what is on somebody's screen changes by the minute.
 *
 * **A window whose process is gone is not open.** The application removes its own files as windows
 * close and as it quits, so anything left behind is the residue of a crash. Rather than believing
 * it, the owning process is checked and a dead one's file is both ignored and cleared away — the
 * one place this program is entitled to delete a file it did not write in this run, because the
 * name says which process did and that process is provably gone.
 */
export function readOpenDocuments(dataDir: string): OpenDocumentsView {
  const files = listSnapshotFiles(dataDir);
  if (files.length === 0) return EMPTY;

  const snapshots: WindowSnapshot[] = [];
  let unreadableWindows = 0;

  for (const { file, snapshotPid } of files) {
    if (!processIsRunning(snapshotPid)) {
      // Deciding it is gone is the answer; clearing it away is only a courtesy, so the two are
      // separated. Another reader may have removed it already, or the directory may be one this
      // process cannot write to — a locked-down data directory, or one owned by another account —
      // and neither is a reason to stop describing the windows that *are* open.
      //
      // Deliberately the narrowest possible catch: it wraps the removal alone, so a directory that
      // cannot be listed and a file that cannot be parsed are still reported rather than swallowed
      // by a guard meant for something else.
      try {
        rmSync(file, { force: true });
      } catch {
        // Left on disk. It will be skipped again next time, for the same reason.
      }
      try {
        removeOpenDocumentContentForProcess(dataDir, snapshotPid);
      } catch {
        // Content is also ignored while its owner is gone. Removal is only cleanup.
      }
      continue;
    }
    const snapshot = readSnapshot(file);
    if (snapshot === null) unreadableWindows += 1;
    else snapshots.push(snapshot);
  }

  if (snapshots.length === 0) return { ...EMPTY, unreadableWindows };

  // Most recently focused first. The window at the front is the one whose tab a person means.
  const ordered = [...snapshots].sort((a, b) => b.focusedAt - a.focusedAt || b.windowId - a.windowId);
  const front = ordered[0]!;
  const activeRef =
    front.activeTabId === null ? null : openDocumentReference(front.pid, front.windowId, front.activeTabId);

  const documents = ordered.flatMap((snapshot) =>
    snapshot.documents.map((record) => {
      const ref = openDocumentReference(snapshot.pid, snapshot.windowId, record.tabId);
      return {
        ...record,
        ref,
        window: snapshot.windowId,
        process: snapshot.pid,
        activeInWindow: snapshot.activeTabId === record.tabId,
        active: ref === activeRef,
      };
    }),
  );

  // The active document first. Every reply that carries this list is bounded, and a bound cuts
  // from the end — so the one document a caller is most likely to have asked about must not be
  // the one a long list pushes out.
  const active = documents.filter((entry) => entry.active);
  const rest = documents.filter((entry) => !entry.active);

  return { windows: snapshots.length, activeRef, documents: [...active, ...rest], unreadableWindows };
}
